version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
    ports:
      - "3306:3306"
    networks:
      - backend

  product-service:
    build: ./product-service
    container_name: product-service
    depends_on:
      - mysql
    ports:
      - "8082:8082"
    networks:
      - backend

  order-service:
    build: ./order-service
    container_name: order-service
    depends_on:
      - product-service
    ports:
      - "8081:8081"
    networks:
      - backend

networks:
  backend:
    driver: bridge
